
- name: Provision Testbed
  hosts: all
  become: yes

  tasks:
    - name: Print selected image
      debug:
        msg: "Deploying Windows Server 2022"

    - name: Simulate blade provisioning
      debug:
        msg: "Configuring blade {item}"
      loop: ['blade1', 'blade2', 'blade3']
